baseURL = 'https://transcal.wiki/'
title = 'Transgender Calendar.wiki'
theme = "PaperMod"

# Language Settings
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "PaperMod"
  Content = """
Welcome to demo of hugo's theme PaperMod.
- **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
- Do give a 🌟 on Github !
- PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/adityatelange/hugo-PaperMod"

  [[params.socialIcons]]
  name = "KoFi"
  url = "https://ko-fi.com/adityatelange"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
